version: '3.8'

services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    restart: unless-stopped
    volumes:
      - ./Client:/app
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8083

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./Server:/app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
