version: '3.8'

services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    restart: unless-stopped
    volumes:
      - ./Client:/app
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8083

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./Server:/app
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_DIALECT=${DB_DIALECT}
      - DB_SSL=${DB_SSL}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - URL_REACT=${URL_REACT}
      - MAX_NUMBER_SCHEDULE=${MAX_NUMBER_SCHEDULE}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - EMAIL_APP=${EMAIL_APP}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - API_KEY_MAP=${API_KEY_MAP}
      - API_KEY_MAP_OPENROUTES=${API_KEY_MAP_OPENROUTES}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
