const actionTypes = Object.freeze({
    // CRUD actions user
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_FAIL: "CREATE_USER_FAIL",
    EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
    EDIT_USER_FAIL: "EDIT_USER_FAIL",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_FAIL: "DELETE_USER_FAIL",

    // CRUD actions UAV
    CREATE_UAV_SUCCESS: "CREATE_UAV_SUCCESS",
    CREATE_UAV_FAIL: "CREATE_UAV_FAIL",
    GET_UAVS_SUCCESS: "GET_UAVS_SUCCESS",
    GET_UAVS_FAIL: "GET_UAVS_FAIL",
})
export default actionTypes;