const actionTypes = Object.freeze({
    // CRUD actions user
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_FAIL: "CREATE_USER_FAIL",
    EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
    EDIT_USER_FAIL: "EDIT_USER_FAIL",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_FAIL: "DELETE_USER_FAIL",

    // CRUD actions UAV
    CHANGE_ACTION_SUCCESS: "CHANGE_ACTION_SUCCESS",
    CHANGE_ACTION_FAIL: "CHANGE_ACTION_FAIL",
    REGISTER_UAV_SUCCESS: "REGISTER_UAV_SUCCESS",
    REGISTER_UAV_FAIL: "REGISTER_UAV_FAIL",
    FETCH_ALL_UAVS_BY_OWNER_SUCCESS: "FETCH_ALL_UAVS_BY_OWNER_SUCCESS",
    FETCH_ALL_UAVS_BY_OWNER_FAIL: "FETCH_ALL_UAVS_BY_OWNER_FAIL",
    CHANGE_STATUS_UAV_SUCCESS: "CHANGE_STATUS_UAV_SUCCESS",
    CHANGE_STATUS_UAV_FAIL: "CHANGE_STATUS_UAV_FAIL",
    FETCH_UAVS_BY_STATUS_AND_OWNER_SUCCESS: "FETCH_UAVS_BY_STATUS_AND_OWNER_SUCCESS",
    FETCH_UAVS_BY_STATUS_AND_OWNER_FAIL: "FETCH_UAVS_BY_STATUS_AND_OWNER_FAIL",
    UPDATE_UAV_SUCCESS: "UPDATE_UAV_SUCCESS",
    UPDATE_UAV_FAIL: "UPDATE_UAV_FAIL",
})
export default actionTypes;